#!/bin/bash

refname="refs/heads/server"

TARGET_BRANCH="refs/heads/server"

if [[ $refname = $TARGET_BRANCH ]]; then

  WORK_DIR=/var/www/ntt/data/www/ntt.avotra.ru/ntt
  GIT_DIR=/var/www/ntt/data/www/ntt.avotra.ru/ntt/repo.git
  
  cd $WORK_DIR || exit 1

  unset GIT_DIR

  git pull origin server

  sudo systemctl restart ntt

  source /var/www/ntt/data/www/ntt.avotra.ru/ntt/venv/bin/activate

  ./manage.py migrate

else
  # No action for other branches
  :
fi
